apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/semever24/argocd-app-of-apps
    targetRevision: master
    path: apps

  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true