apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/semever24/argocd-app-of-apps
    targetRevision: master
    path: apps/guestbook

  destination:
    name: k8s-user@app-of-apps.ap-south-1.eksctl.io
    namespace: guestbook

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true